"""0004 Add deleted field

Revision ID: eba11657ea9a
Revises: ff5c13a3f8b7
Create Date: 2025-04-02 21:33:19.190244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba11657ea9a'
down_revision = 'ff5c13a3f8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), server_default='False', nullable=False))

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), server_default='False', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
