"""0003 Add autor's surname field

Revision ID: ff5c13a3f8b7
Revises: 1edbd8ea8442
Create Date: 2025-03-31 20:35:46.696921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5c13a3f8b7'
down_revision = '1edbd8ea8442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=32), server_default='', nullable=False))
        batch_op.drop_index('ix_authors_name')
        batch_op.create_unique_constraint('AuthorFullNameConstrant', ['name', 'surname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_constraint('AuthorFullNameConstrant', type_='unique')
        batch_op.create_index('ix_authors_name', ['name'], unique=1)
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
